//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerMILLVERICUTInterfacePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerMILLVERICUTInterfacePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the Machine File from the Project file..
        /// </summary>
        internal static string IDFS_FailMachineFileRead {
            get {
                return ResourceManager.GetString("IDFS_FailMachineFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory is not empty. ALL EXISTING FILES WILL BE DELETED! Do you want to continue?.
        /// </summary>
        internal static string IDS_DirNotEmpty {
            get {
                return ResourceManager.GetString("IDS_DirNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} doesn&apos;t exist..
        /// </summary>
        internal static string IDS_DirNotExist {
            get {
                return ResourceManager.GetString("IDS_DirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured. Please contact your system supplier. Exception details:\n%s.
        /// </summary>
        internal static string IDS_Exception {
            get {
                return ResourceManager.GetString("IDS_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting model workplane:\n%s.
        /// </summary>
        internal static string IDS_ExGetModelWorkplane {
            get {
                return ResourceManager.GetString("IDS_ExGetModelWorkplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting NC Program workplane:\n%s.
        /// </summary>
        internal static string IDS_ExGetNCProgWorkplane {
            get {
                return ResourceManager.GetString("IDS_ExGetNCProgWorkplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export project..
        /// </summary>
        internal static string IDS_ExportErrors {
            get {
                return ResourceManager.GetString("IDS_ExportErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy NC Program(s)..
        /// </summary>
        internal static string IDS_ExportNCCopyFailed {
            get {
                return ResourceManager.GetString("IDS_ExportNCCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export solids..
        /// </summary>
        internal static string IDS_ExportSolidsFailed {
            get {
                return ResourceManager.GetString("IDS_ExportSolidsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get workplanes info..
        /// </summary>
        internal static string IDS_ExportWorkPlaneFailed {
            get {
                return ResourceManager.GetString("IDS_ExportWorkPlaneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} doesn&apos;t exist..
        /// </summary>
        internal static string IDS_FileNotExist {
            get {
                return ResourceManager.GetString("IDS_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;%s&apos; can&apos;t be created..
        /// </summary>
        internal static string IDS_FolderNotCreated {
            get {
                return ResourceManager.GetString("IDS_FolderNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File %s corresponding to NC Program &apos;%s&apos; doesn&apos;t exist..
        /// </summary>
        internal static string IDS_NCFileDoesntExist {
            get {
                return ResourceManager.GetString("IDS_NCFileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No NC Programs were selected for output..
        /// </summary>
        internal static string IDS_NCNoProgsSelected {
            get {
                return ResourceManager.GetString("IDS_NCNoProgsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of NC Program &apos;%s&apos; is &apos;%s&apos;. Make sure that the program is written and up to date..
        /// </summary>
        internal static string IDS_NCStatusWrong {
            get {
                return ResourceManager.GetString("IDS_NCStatusWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your NC Program..
        /// </summary>
        internal static string IDS_NCVerify {
            get {
                return ResourceManager.GetString("IDS_NCVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component {0} do not exist in the setup {1}..
        /// </summary>
        internal static string IDS_NoComponent {
            get {
                return ResourceManager.GetString("IDS_NoComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component {0} do not exist in the setup {1}..
        /// </summary>
        internal static string IDS_InvalidWorkOffset
        {
            get {
                return ResourceManager.GetString("IDS_InvalidWorkOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory not specified..
        /// </summary>
        internal static string IDS_NoOutputDirectory {
            get {
                return ResourceManager.GetString("IDS_NoOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is not available. Please create and save PowerMill project..
        /// </summary>
        internal static string IDS_NoProject {
            get {
                return ResourceManager.GetString("IDS_NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setups specified..
        /// </summary>
        internal static string IDS_NoSetups {
            get {
                return ResourceManager.GetString("IDS_NoSetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vericut template not specified..
        /// </summary>
        internal static string IDS_NoVericutTemplate {
            get {
                return ResourceManager.GetString("IDS_NoVericutTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template file may contain a design, would you like to remove it from the output project?.
        /// </summary>
        internal static string IDS_RemoveDesign {
            get {
                return ResourceManager.GetString("IDS_RemoveDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template file may contain a fixture, would you like to remove it from the output project?.
        /// </summary>
        internal static string IDS_RemoveFixture {
            get {
                return ResourceManager.GetString("IDS_RemoveFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template file may include NC programs, would you like to remove these from the output project?.
        /// </summary>
        internal static string IDS_RemoveNCCode {
            get {
                return ResourceManager.GetString("IDS_RemoveNCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template file may contain a stock, would you like to remove it from the output project?.
        /// </summary>
        internal static string IDS_RemoveStock {
            get {
                return ResourceManager.GetString("IDS_RemoveStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup: {0}..
        /// </summary>
        internal static string IDS_SetupName {
            get {
                return ResourceManager.GetString("IDS_SetupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project exported successfully..
        /// </summary>
        internal static string IDS_SuccessfullExport {
            get {
                return ResourceManager.GetString("IDS_SuccessfullExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select VERICUT template file.
        /// </summary>
        internal static string IDS_TemplateSelectDlgTitle {
            get {
                return ResourceManager.GetString("IDS_TemplateSelectDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool &apos;%s&apos; doesn&apos;t have a holder. Would you like to continue?.
        /// </summary>
        internal static string IDS_ToolNoHolder {
            get {
                return ResourceManager.GetString("IDS_ToolNoHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool &apos;%s&apos; doesn&apos;t have a shank. Would you like to continue?.
        /// </summary>
        internal static string IDS_ToolNoShank {
            get {
                return ResourceManager.GetString("IDS_ToolNoShank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool number for tool &apos;%s&apos; isn&apos;t set, which will cause problems in VERICUT. Would you like to stop export and change the value in Tool properties dialog?.
        /// </summary>
        internal static string IDS_ToolNumberNotSet {
            get {
                return ResourceManager.GetString("IDS_ToolNumberNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool number for tool &apos;%s&apos; isn&apos;t unique. All tools numbers in exported nc programs must be unique for tools to work properly in VERICUT..
        /// </summary>
        internal static string IDS_ToolNumberNotUnique {
            get {
                return ResourceManager.GetString("IDS_ToolNumberNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the .Vericut file..
        /// </summary>
        internal static string IDS_VCCreateVericutFileFail {
            get {
                return ResourceManager.GetString("IDS_VCCreateVericutFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find VERICUT..
        /// </summary>
        internal static string IDS_VCNotFound {
            get {
                return ResourceManager.GetString("IDS_VCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to start VERICUT and load project?.
        /// </summary>
        internal static string IDS_VCStartAndLoadQuest {
            get {
                return ResourceManager.GetString("IDS_VCStartAndLoadQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vericut template &apos;%s&apos; can&apos;t be read..
        /// </summary>
        internal static string IDS_VericutTemplateReadFailure {
            get {
                return ResourceManager.GetString("IDS_VericutTemplateReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block isn&apos;t specified..
        /// </summary>
        internal static string IDS_VerifBlockNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifBlockNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one block .stl file should be selected..
        /// </summary>
        internal static string IDS_VerifBlockSTLNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifBlockSTLNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory does not exist..
        /// </summary>
        internal static string IDS_VerifDirDoesntExist {
            get {
                return ResourceManager.GetString("IDS_VerifDirDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory path isn&apos;t specified..
        /// </summary>
        internal static string IDS_VerifDirNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifDirNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model .stl file path isn&apos;t specified..
        /// </summary>
        internal static string IDS_VerifModelSTLNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifModelSTLNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No NC Programs have been selected..
        /// </summary>
        internal static string IDS_VerifNCProgNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifNCProgNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock model name isn&apos;t specified..
        /// </summary>
        internal static string IDS_VerifStockModelNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifStockModelNotSpecified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stock model {0} doesn&apos;t exist.
        /// </summary>
        internal static string IDS_NoStockModel
        {
            get {
                return ResourceManager.GetString("IDS_NoStockModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Model {0} doesn&apos;t exist.
        /// </summary>
        internal static string IDS_NoModel
        {
            get {
                return ResourceManager.GetString("IDS_NoModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Model {0} doesn&apos;t exist.
        /// </summary>
        internal static string IDS_NCProgramDoesntExist
        {
            get {
                return ResourceManager.GetString("IDS_NCProgramDoesntExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Model {0} doesn&apos;t exist.
        /// </summary>
        internal static string IDS_ToolpathDoesntExist
        {
            get {
                return ResourceManager.GetString("IDS_ToolpathDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inipar.set file path isn&apos;t specified..
        /// </summary>
        internal static string IDS_VerifVMIniparNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifVMIniparNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine file path isn&apos;t specified..
        /// </summary>
        internal static string IDS_VerifVMMachineNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifVMMachineNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all VERICUT settings have been set..
        /// </summary>
        internal static string IDS_VerifVMSettingsNotSpecified {
            get {
                return ResourceManager.GetString("IDS_VerifVMSettingsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inipar.set file path is incorrect..
        /// </summary>
        internal static string IDS_VMIniparPathIncorrect {
            get {
                return ResourceManager.GetString("IDS_VMIniparPathIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine file path is incorrect..
        /// </summary>
        internal static string IDS_VMMachinePathIncorrect {
            get {
                return ResourceManager.GetString("IDS_VMMachinePathIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;%s&apos; doesn&apos;t exist. It&apos;s necessary to extract data from VERICUT machine and inipar.set files..
        /// </summary>
        internal static string IDS_VMMachineReaderNotFound {
            get {
                return ResourceManager.GetString("IDS_VMMachineReaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find VERICUT machine file reader..
        /// </summary>
        internal static string IDS_VMMachineReaderNotFound1 {
            get {
                return ResourceManager.GetString("IDS_VMMachineReaderNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of NC Program workplanes exceeded maximum amount allowed. Workplane %s won&apos;t be set in VERICUT project..
        /// </summary>
        internal static string IDS_VMTooManyWorkplanes {
            get {
                return ResourceManager.GetString("IDS_VMTooManyWorkplanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work offset you&apos;re trying to add is already the list..
        /// </summary>
        internal static string IDS_WorkOffsetExists {
            get {
                return ResourceManager.GetString("IDS_WorkOffsetExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplane &apos;%s&apos; doesn&apos;t exist..
        /// </summary>
        internal static string IDS_WorkplaneDoesntExist {
            get {
                return ResourceManager.GetString("IDS_WorkplaneDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract workplane properties..
        /// </summary>
        internal static string IDS_WorkplaneFailedToExtract {
            get {
                return ResourceManager.GetString("IDS_WorkplaneFailedToExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get workplane properties..
        /// </summary>
        internal static string IDS_WorkplaneFailedToGet {
            get {
                return ResourceManager.GetString("IDS_WorkplaneFailedToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model location workplane isn&apos;t set for NC Program &apos;%s&apos;..
        /// </summary>
        internal static string IDS_WorkplaneModelNotSet {
            get {
                return ResourceManager.GetString("IDS_WorkplaneModelNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Model location workplane isn&apos;t set for NC Program &apos;%s&apos;..
        /// </summary>
        internal static string IDS_NoTemplateVerification
        {
            get
            {
                return ResourceManager.GetString("IDS_NoTemplateVerification", resourceCulture);
            }
        }
    }
}
